### ISSUE TITLE
Связать сервер и приложение

### ISSUE THREAD

**Issue by degoz16** [dzaikov/sandbags-app#4]
- [x] Научиться отправлять запросы серверу
- [x] Научиться принимать json с параметрами с сервера
- [x] Сделать парсинг json
- [x]  Сделать перемещение полученных данных на карту

**Comment by jaguar13337** [comment]
JsonReader лежит в Android SDK, поэтому в UnitTest's его нельзя использовать. Ошибки не было.

**Comment by degoz16** [comment]
Нужно немного подправить json на сервере и упростить его (как следствие парсинг), +добавлю на всякий случай проверки в коде на длину полученного от сервера списка

**Comment by degoz16** [comment]
все, закрываю
